### ISSUE TITLE
Allow taking a given quantity from buckets and traps

### ISSUE THREAD

**Issue by vxid** [nroutasuo/level13#159] opened 2020-02-05 08:48 UTC
**Game version**
Latest

**Description**
It would be pretty useful to only pick a chosen quantity off buckets and traps, instead of only being able to take everything.

**Comment by nroutasuo** [comment] 2020-02-05 19:08
I'm definitely still planning to fix this at some point but I'm closing this issue as it's a duplicate of #8.

**Closed by nroutasuo** 2020-02-05 19:08 UTC
