### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of undefined (reading 'Injury')

### ISSUE THREAD

**Issue by freakwilly** [nroutasuo/level13#257] opened 2022-05-10 18:52 UTC
Details:
[I had moved to a new square and got injured.  I was on the 14th floor.  As soon as I pressed the OK button on the injury, I clicked the bag tab and clicked "use kit", then the error popped up.]

Seed: 2835
Position: 14.8.10 (inCamp: false)
Stacktrace:
TypeError: Cannot read properties of undefined (reading 'Injury')
    at constructor.useItem (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.2:1657:32)
    at constructor.performAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.2:243:27)
    at constructor.startAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.2:136:10)
    at m.fn.init.<anonymous> (https://nroutasuo.github.io/level13/src/game/UIFunctions.js?v=0.4.2:195:57)
    at HTMLButtonElement.<anonymous> (https://nroutasuo.github.io/level13/src/core/ExceptionHandler.js?v=0.4.2:11:18)
    at HTMLButtonElement.dispatch (https://nroutasuo.github.io/level13/lib/jquery//jquery-1.11.1.min.js?v=0.4.2:3:8436)
    at HTMLButtonElement.r.handle (https://nroutasuo.github.io/level13/lib/jquery//jquery-1.11.1.min.js?v=0.4.2:3:5139)

**Comment by nroutasuo** [comment] 2022-05-11 18:54
Thanks for the details! I'll close this ticket since it's a duplicate of #252 but will post a fix soon.

**Closed by nroutasuo** 2022-05-11 18:54 UTC
