### ISSUE TITLE
Tiny map generation

### ISSUE THREAD

**Issue by Pimhazeveld** [nroutasuo/level13#22] opened 2018-03-23 18:32 UTC
https://imgur.com/a/cGyI9#WKxTeeJ This map just consists of 14 tiles in a straight line. Too small to do really anything.

A suggestion to solve this would be checking after the map generation how many tiles it has and if it isn't enough it resets and tries again.

**Comment by HeinousTugboat** [comment] 2018-03-23 18:44
I had this happen to me on level 12 once. It turns out the rest of the level actually *was* there, it just wasn't connected. The map generation definitely needs some sanity checks attached to it.

**Comment by primeprover** [comment] 2018-03-24 13:08
I have just hit this on lvl 11. Is there a way around this? There is no stairs to another level

**Comment by HeinousTugboat** [comment] 2018-03-24 13:15
Not that I'm aware of. If it's a local save you can use cheats to teleport, but I wound up starting over. If you could, can you mark down the game seed? I can help you find it later today if you have trouble.

**Comment by primeprover** [comment] 2018-03-24 13:49
It isn't a local save. How can I find the seed?

**Comment by HeinousTugboat** [comment] 2018-03-24 15:02
You can either put this in the address bar (make sure to add the `javascript:` at the beginning, most browsers won't let you paste it):

`javascript:alert('World Seed: '+JSON.parse(localStorage.getItem('gameState')).worldSeed)`

Or you can hit `F12` and paste this in and hit enter:

`console.clear();console.log('%cWorld Seed: %c'+JSON.parse(localStorage.getItem('gameState')).worldSeed,'font-size:24px;color:blue','font-size:30px;color:black')`

Either way will give you the seed that's currently saved to that specific URL and browser. 😄

**Comment by primeprover** [comment] 2018-03-24 15:08
The seed was 8463

**Comment by HeinousTugboat** [comment] 2018-03-27 12:29
Here's another snippet, this one will let you enter a seed when you click restart and build the world with the new seed. This way we can manually check out specific seeds. This also might be helpful for #36.

`$('#btn-restart').one("click",function() { let n = parseInt(prompt('Seed number?')); require.s.contexts._.defined['game/worldcreator/WorldCreatorRandom'].getNewSeed = () => n; })`

**Comment by tasonir** [comment] 2018-03-28 23:12
I attempted to reproduce this but man it takes a long time to get down to level 11 starting from scratch.  I'm going to give up and just assume the original report is true :)

**Comment by primeprover** [comment] 2018-03-29 08:11
I could provide a save if exporting was implemented.
It should be possible to give yourself a boost in order to make it through the game quickly using the console. Try cheating using https://nroutasuo.github.io/level13/?file:///

**Comment by nroutasuo** [comment] 2018-03-29 10:57
Thank you for all the seeds and details so far! With these it should be possible for me to track down the problem. I suspect it's a problem in the "random" number generation but could also be that some of the checks for max / min sectors per level or line just aren't working.

**Comment by Tharg44** [comment] 2018-04-09 22:12
I have a similar issue with my seed 5587
https://imgur.com/a/7LJfq

**Comment by nroutasuo** [comment] 2018-06-26 22:32
The problem with disconnected levels has been fixed in master and will be fixed in the next update. Thank you again for the reports!

I'll definitely look into some more sanity checks for the whole generation in the future.

**Closed by nroutasuo** 2018-06-26 22:32 UTC
Labels: bug
