### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'toggleClass' of undefined

### ISSUE THREAD

**Issue by desci** [nroutasuo/level13#93] opened 2019-01-30 09:25 UTC
Details:
Switching tabs on Level 11

Stacktrace:
TypeError: Cannot read property 'toggleClass' of undefined
    at constructor.updateButtonCalloutCosts (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:237:27)
    at constructor.updateButtonCallout (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:205:26)
    at constructor.updateButtons (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:157:9)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:134:18)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment] 2019-02-01 20:35
Hi! This is a duplicate of a bug #85 that's already fixed (but the fix is not released yet) so I'm closing it but thank you for reporting!

**Closed by nroutasuo** 2019-02-01 20:35 UTC
