### ISSUE TITLE
[JS Error] Canceling recruitment causes a "ReferenceError: item is not defined" crash

### ISSUE THREAD

**Issue by quietsamurai98** [nroutasuo/level13#79] opened 2018-08-20 21:21 UTC
Details:
Hit the recruit button, then hit cancel immediately.

Stacktrace:
ReferenceError: item is not defined
    at constructor.refreshCurrent (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:61:107)
    at constructor.initializePopup (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:43:18)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:36:22)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment] 2018-08-21 19:57
Thanks for reporting! As @Unihedro noticed it's a duplicate of a previously reported bug so I'll close this ticket but I'll definitely look into fixing it.

**Closed by nroutasuo** 2018-08-21 19:57 UTC
Labels: bug, exception
