### ISSUE TITLE
[JS Error] TypeError: worldVO is undefined

### ISSUE THREAD

**Issue by Phi161803** [nroutasuo/level13#231] opened 2022-04-27 12:09 UTC
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]
Tried the link from reddit. Literally the first thing that happened was the error. Refreshed multiple times, no difference
Seed: 5642
Position: 13.0.0 (inCamp: false)
Stacktrace:
loadWorld/</<@https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:233:38

**Comment by nroutasuo** [comment] 2022-04-27 17:17
Thank you for reporting! This looks like it could be due to some old data - have you played the game previously? If so, clearing local data for the page should help.

**Comment by nroutasuo** [comment] 2023-12-20 21:22
I've not been able to reproduce this and haven't seen any more reports so I will close this issue now. Hope you managed to get it working for you!

**Closed by nroutasuo** 2023-12-20 21:22 UTC
Labels: bug
