### ISSUE TITLE
[JS Error] ReferenceError: item is not defined

### ISSUE THREAD

**Issue by colindeclue** [nroutasuo/level13#83] opened 2018-08-23 14:34 UTC
Details:
Was looking at the "recruit" menu after having 1/1 followers. Additionally, followers don't seem to add any attack.

Stacktrace:
ReferenceError: item is not defined
    at constructor.refreshCurrent (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:61:107)
    at constructor.initializePopup (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:43:18)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:36:22)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment] 2018-08-25 09:58
Thanks for reporting! This is a duplicate of #76 so I'll close this one but I'll definitely look into fixing it.

**Closed by nroutasuo** 2018-08-25 09:58 UTC
