### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of null (reading 'description')

### ISSUE THREAD

**Issue by Razenpok** [nroutasuo/level13#284] opened 2023-07-16 10:33 UTC
Details:
Nothing special, just walking around level 18

Seed: 3964
Position: 18.-12.9 (inCamp: true)
Stacktrace:
TypeError: Cannot read properties of null (reading 'description')
    at constructor.getDescription (https://nroutasuo.github.io/level13/src/game/helpers/PlayerActionsHelper.js?v=0.5.1:2051:19)
    at constructor.generateActionButtonCallout (https://nroutasuo.github.io/level13/src/game/UIFunctions.js?v=0.5.1:398:55)
    at HTMLDivElement.<anonymous> (https://nroutasuo.github.io/level13/src/game/UIFunctions.js?v=0.5.1:371:26)
    at HTMLDivElement.<anonymous> (https://nroutasuo.github.io/level13/lib/jquery/jquery-1.11.1.min.js?v=0.5.1:3:22541)
    at Function.each (https://nroutasuo.github.io/level13/lib/jquery/jquery-1.11.1.min.js?v=0.5.1:2:2973)
    at m.fn.init.each (https://nroutasuo.github.io/level13/lib/jquery/jquery-1.11.1.min.js?v=0.5.1:2:835)
    at m.fn.init.domManip (https://nroutasuo.github.io/level13/lib/jquery/jquery-1.11.1.min.js?v=0.5.1:3:22499)
    at m.fn.init.after (https://nroutasuo.github.io/level13/lib/jquery/jquery-1.11.1.min.js?v=0.5.1:3:20959)
    at HTMLDivElement.<anonymous> (https://nroutasuo.github.io/level13/src/game/UIFunctions.js?v=0.5.1:363:17)
    at Function.each (https://nroutasuo.github.io/level13/lib/jquery/jquery-1.11.1.min.js?v=0.5.1:2:2973)

**Comment by CondoSlime** [comment] 2023-07-16 14:12
Seems to be the same thing as what I had. It's caused by trying to view your inventory while a newspaper is in there.

**Comment by nroutasuo** [comment] 2023-07-16 14:18
Yep looks the same. I'll close this as a duplicate but thank you for reporting anyway! Will fix for next version.

**Closed by nroutasuo** 2023-07-16 14:18 UTC
