### ISSUE TITLE
Floor -1 -> game is breaking without any action from my side [JS Error] TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by MikeSzym** [nroutasuo/level13#242] opened 2022-05-01 18:13 UTC
What happened - I entered floor -1, walked around, stamina went down so I pressed "rest". And the game threw error. Ok, reload, not touching anything (was writing DM on Reddit) and without any interaction - happened again

I can't attach a save file from right before the crash as the game auto saved post crash-bug... I am testing if loading that save backup in incognito will auto-crash after a few minutes as well, but I probably did it before sending the expedition :( It was the last one, max food for metal

Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

Seed: 9342
Position: -1.7.1 (inCamp: false)
Stacktrace:
TypeError: Cannot read properties of null (reading 'get')
    at constructor.moveCurrencyFromBagToCamp (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:39)
    at constructor.sendCaravan (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9)
    at constructor.performAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31)
    at constructor.updateNode (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29)

**Comment by nroutasuo** [comment] 2022-05-01 19:47
Thanks for reporting! This is a duplicate of #232 so I'll close this ticket but a fix will be included in the next bugfix update.

**Closed by nroutasuo** 2022-05-01 19:47 UTC
