### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of null (reading 'get') Cannot Load Save

### ISSUE THREAD

**Issue by Heitomos** [nroutasuo/level13#240] opened 2022-04-30 19:20 UTC
Details:
I was exploring floor 9, about my third dive down. I had made a Trap and was waiting for food, so I tabbed to something else. I came back to this error, and can no long load my save.

Seed: 1369
Position: 9.1.12 (inCamp: false)
Stacktrace:
TypeError: Cannot read properties of null (reading 'get')
    at constructor.moveCurrencyFromBagToCamp (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:39)
    at constructor.sendCaravan (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9)
    at constructor.performAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31)
    at constructor.updateNode (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29)

**Comment by nroutasuo** [comment] 2022-05-01 16:32
Thank you for reporting! I'm closing this issue since it's a duplicate of #232 but I will post a new version of the game with a fix for this in the near future.

**Closed by nroutasuo** 2022-05-01 16:32 UTC
