### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by bpromas** [nroutasuo/level13#238] opened 2022-04-30 10:30 UTC
Details:
I was just beginning to explore level 6 (I'm pretty sure) and I had just found a camp after scouting a location on the map. A couple seconds later this bug happened and reloading the page does not fix it, the bug just comes up again after a couple seconds in a blank page. Unfortunately I can't see anything about my game as all I see is a blank page so I don't know exactly what I was carrying with me or what I had in my camps, I just know I did not have sufficient metal to build the camp. 

I don't recall clicking anything after scouting the location, but if I did click something it may have been to scavenge for metal.

Seed: 2997
Position: 6.-1.-12 (inCamp: false)
Stacktrace:
TypeError: Cannot read properties of null (reading 'get')
    at constructor.moveCurrencyFromBagToCamp (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:39)
    at constructor.sendCaravan (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9)
    at constructor.performAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31)
    at constructor.updateNode (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29)

**Comment by nroutasuo** [comment] 2022-04-30 12:43
Thank you for reporting this! It looks like a duplicate of #232 so I am closing this issue, but I appreciate the details provided here.

**Closed by nroutasuo** 2022-04-30 12:43 UTC
