### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by SoffixTiger** [nroutasuo/level13#239] opened 2022-04-30 19:05 UTC
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

Seed: 9518
Position: 9.11.-5 (inCamp: false)
Stacktrace:
TypeError: Cannot read properties of null (reading 'get')
    at constructor.moveCurrencyFromBagToCamp (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:39)
    at constructor.sendCaravan (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9)
    at constructor.performAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31)
    at constructor.updateNode (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29)

**Comment by nroutasuo** [comment] 2022-05-01 16:31
Thanks for reporting this! I'm closing the issue because it's a duplicate of #232 but will update the game with a fix soon.

**Closed by nroutasuo** 2022-05-01 16:31 UTC
