### ISSUE TITLE
[JS Error] TypeError: playerLevelCamp is null

### ISSUE THREAD

**Issue by HiPtich** [nroutasuo/level13#241] opened 2022-05-01 09:54 UTC
Details:
[can't continue playing. "you've found a bug", after first elevator, afk in background on level 4. firefox 99.0.1(64), windows 7 x64 home basic]

Seed: 1987
Position: 4.0.-11 (inCamp: false)
Stacktrace:
moveCurrencyFromBagToCamp@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:23
sendCaravan@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9
performAction@https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31
updateNode@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34
update@https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10
update@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165
update@https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16
execute@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611
dispatch@https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738
tick@https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29

**Comment by nroutasuo** [comment] 2022-05-01 16:33
Thanks for the bug report! I'll close this issue since it's a duplicate of #233 but I'll post a new version of the game with a fix soon.

**Closed by nroutasuo** 2022-05-01 16:33 UTC
