### ISSUE TITLE
Add multiplayer 

### ISSUE THREAD

**Issue by MasterCard69** [nroutasuo/level13#267] opened 2022-08-11 11:43 UTC
**Game version**
V 0.4.3

**Description**
Can you add multiplayer

**Comment by Mr-critic** [comment] 2022-08-11 12:29
Pls do. =)

**Comment by PugGamer870** [comment] 2022-08-11 16:17
Yes

**Comment by nroutasuo** [comment] 2022-08-11 18:08
I'll close this one since it's a duplicate of #265

**Closed by nroutasuo** 2022-08-11 18:08 UTC
