### ISSUE TITLE
Build Collection

### ISSUE THREAD

**Issue by oddare** [nroutasuo/level13#8] opened 2018-03-21 14:59 UTC
Currently, you can only collect up till how much space you have in your backpack or water/food you have available to be collected. This, in turn, forces you to take a full amount of one thing, scavenge and then ditch the surplus to make room for another, effectively losing out on potentially a lot of resources.

A fix to this could perhaps be to add a button to take "1", "5", "10" or "max/all".

**Comment by praxiq** [comment] 2018-03-27 22:18
This annoyed me at first. The inability to collect a small amount of a resource when exploring makes absolutely no logical sense.

But then again... it also doesn't make sense that a bow and arrow can only shoot in orthogonal directions, yet almost every fantasy roguelike has this restriction, and it makes the gameplay deeper and more strategic. 

Sometimes, keeping things "too simple" adds emergent complexity to gameplay. Too much realism can be boring. Giving the player lots of options means there's always an option that's "just right" - but sometimes it's better when the player has to try to decide which of two bad options is less bad, when they're both bad in different ways.

In this case, as weird as it was at first, deciding what order to collect which resources so I don't accidentally end up with too much of one thing overfilling my inventory is actually an interesting challenge, and one I've come to enjoy as I explore. So what if it doesn't make sense? Feel free to "fix" it if you want, but also feel free to say "it's by design" and leave it as is.

**Comment by oddare** [comment] 2018-03-27 22:53
While I understand the side of looking at it as a "feature" I posted this after I got into the habit of upgrading both food and water stations to some 20-30 levels. At that point the game becomes artificially longer to work around a "design".

Obviously, if that's a wanted design, for all means.

**Comment by nroutasuo** [comment] 2018-03-28 18:27
I am planning to add this if I can find a way to do it without cluttering the UI too much. On one hand it'd be nice to have, but on the other it's usually not a good idea to give players too many choices.

**Comment by desci** [comment] 2018-05-04 18:47
A simpler way to address this in the short run would be to add a button to discard items. This would prevent having to scavenge to discard stuff.

**Comment by Xetaxheb** [comment] 2019-10-05 21:23
Just add a [1] next to collect...

**Comment by Xetaxheb** [comment] 2019-10-05 21:23
Or make collect only do 1 anyway, it's not like you need to pick up 50 water unless you're filling a storage

**Comment by nroutasuo** [comment] 2022-01-11 19:33
The current live version (0.3.3) has a "collect 1" button so I'm closing this.

**Closed by nroutasuo** 2022-01-11 19:33 UTC
Labels: feature-request
