### ISSUE TITLE
Double recruit bug

### ISSUE THREAD

**Issue by CondoSlime** [nroutasuo/level13#123] opened 2019-04-14 01:14 UTC
**Game version**
0.2.4

**Browser**
Chrome

**Description**
I recruited a person with 9 attack while having 0/2 party members and the game ended up giving me 2 9 attack members instead of 1

**Comment by Centritide** [comment] 2019-05-08 04:31
I've noticed this multiple times. Most hilariously I had a +10 follower, and upon recruiting another, I was given 4 more, for a total of five +10 followers.

**Comment by desci** [comment] 2019-05-10 16:45
Duplicate of #99 #114 but I'm here to give one more confirmation to the bug.

This is what I got after dismissing a +5 follower and recruiting a +7 follower with a 1 follower cap:

![issue123a](https://user-images.githubusercontent.com/2027447/57542754-e6d33c00-7328-11e9-8886-ea3e73384016.png)
![issue123b](https://user-images.githubusercontent.com/2027447/57542753-e6d33c00-7328-11e9-9880-bbac55baf385.png)
![issue123c](https://user-images.githubusercontent.com/2027447/57542752-e6d33c00-7328-11e9-8a95-d0dca497c41d.png)

Savegame: [2019-05-10-13-44_seed1241-level9.txt](https://github.com/nroutasuo/level13/files/3167407/2019-05-10-13-44_seed1241-level9.txt)

**Comment by nroutasuo** [comment] 2020-01-26 20:22
I've seen this once or twice but I have not been able to reliably reproduce or fix. I've added a little fallback to the upcoming version that should ensure you at least won't go over your max follower limit, but the root cause is still under investigation.

**Comment by nroutasuo** [comment] 2022-01-11 20:22
I haven't managed to track down the root cause but it seems to be working well enough in the current version so I'm closing this issue for now.

**Closed by nroutasuo** 2022-01-11 20:22 UTC
Labels: bug
