### ISSUE TITLE
Loot screen continue button issue

### ISSUE THREAD

**Issue by JayL1F3** [nroutasuo/level13#7] opened 2018-03-21 01:19 UTC
Occasionally while fighting a monster and looting it, on the second loot screen the continue button will sometimes do nothing. 

Occasionally clicking an arrow will cause no feedback. Number does not increase or decrease. Reload is necessary.

**Comment by telly23** [comment] 2018-03-21 05:48
I noticed too that sometimes buttons stop responding.

I however have a clue as why the button on the loot screen do nothing sometimes. This happened to me when my inventory was full after a fight. This may have to do with the fact that the total loot is too much for the space left in your inventory. Since the popup tries to take every item, but you have not enough place, nothing happens.

The solution would be to add a "Leave this here" button so you can leave some loot or other objects from your inventory.

**Comment by nroutasuo** [comment] 2018-03-21 17:22
Renaming this to reflect the discussion on the loot screen & making a separate issue for the arrows. Will look into fixing both.

**Comment by desci** [comment] 2018-05-04 18:51
This particular bug is annoying because sometimes a page refresh will mess up the progress if it hasn't been properly saved.

I *think* I can reproduce this behaviour whenever I end up in a combat after scavenging at least once in a cell.

**Comment by strangenoora** [comment] 2018-07-04 21:05
This has now been fixed in master and the fix will be in the next update. Thanks for reporting!

**Comment by nroutasuo** [comment] 2018-07-04 21:06
This has now been fixed in master and the fix will be in the next update. Thanks for reporting!

**Closed by nroutasuo** 2018-07-04 21:06 UTC
Labels: bug
