### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by bkim4** [nroutasuo/level13#244] opened 2022-05-01 23:57 UTC
Details:
just walking around?

Seed: 143
Position: 8.-10.1 (inCamp: false)
Stacktrace:
TypeError: Cannot read properties of null (reading 'get')
    at constructor.moveCurrencyFromBagToCamp (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:413:39)
    at constructor.sendCaravan (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:947:9)
    at constructor.performAction (https://nroutasuo.github.io/level13/src/game/PlayerActionFunctions.js?v=0.4.1:258:31)
    at constructor.updateNode (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:57:34)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/PlayerActionSystem.js?v=0.4.1:31:10)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:15165)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/GameManager.js?v=0.4.1:102:16)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js?v=0.4.1:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js?v=0.4.1:48:29)

**Comment by nroutasuo** [comment] 2022-05-02 18:49
Thanks for reporting! This looks like a duplicate of #232 so I'll close this ticket, but I'll post an update with a fix soon.

**Closed by nroutasuo** 2022-05-02 18:49 UTC
